# Form implementation generated from reading ui file '/Users/jackypc/Documents/AllProjects/Python/autoPortage/UI/UI_main.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(811, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(20, 20, 20, 10)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.bn_run = QtWidgets.QPushButton(parent=self.centralwidget)
        self.bn_run.setObjectName("bn_run")
        self.horizontalLayout.addWidget(self.bn_run)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tview = QtWidgets.QTableView(parent=self.centralwidget)
        self.tview.setObjectName("tview")
        self.verticalLayout.addWidget(self.tview)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 811, 21))
        self.menubar.setObjectName("menubar")
        self.menuMenus = QtWidgets.QMenu(parent=self.menubar)
        self.menuMenus.setObjectName("menuMenus")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionMenus = QtGui.QAction(parent=MainWindow)
        self.actionMenus.setObjectName("actionMenus")
        self.actionRun = QtGui.QAction(parent=MainWindow)
        self.actionRun.setObjectName("actionRun")
        self.menuMenus.addAction(self.actionRun)
        self.menubar.addAction(self.menuMenus.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Url"))
        self.bn_run.setText(_translate("MainWindow", "run"))
        self.menuMenus.setTitle(_translate("MainWindow", "Menus"))
        self.actionMenus.setText(_translate("MainWindow", "Menus"))
        self.actionRun.setText(_translate("MainWindow", "Run"))
